#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


### Initialization ###
SCMODULES=""
TRAPS=""


### Global functions ###

# Call a submodule
subcall() {
  local mod="$1"; shift
  local sub="$1"; shift
  if [ "${sub:0:1}" = "_" ]; then
    echo "Cannot call $mod $sub: private function"
  fi
  if [ "$(type -t "${mod}_$sub")" = "function" ]; then
    "${mod}_$sub" "$@"
  else
    echo "Cannot find $SC $mod $sub"
    exit 1
  fi
}

# Tell if a submodule supports a function
cancall() {
  local mod="$1"; shift
  local sub="$1"; shift
  if [ "$(type -t "${mod}_$sub")" = "function" ]; then
    return 0
  fi
  return 1
}

# Import a common module
require() {
  local mod="$1"; shift
  local setup="$1"; shift || true

  if [[ " $SCMODULES " != *" $mod "* ]]; then
    if [ -r "$SCLIBDIR/$mod" ]; then
      source "$SCLIBDIR/$mod"
    elif [ -r "$SCCMDDIR/$mod" ]; then
      source "$SCCMDDIR/$mod"
    else
      echo "Required module $mod not found"
      exit 2
    fi
    # Add the main entry point
    eval "$mod() { subcall $mod \"\$@\"; }"
    SCMODULES="$SCMODULES $mod"
  fi

  if [ "$setup" = setup ]; then
    if [ "$(type -t "${mod}_ready")" = "function" ] && [ "$(type -t "${mod}_setup")" = "function" ] && ! "$mod" ready; then
      "$mod" setup
    fi
  elif [ "$setup" = ready ]; then
    if [ "$(type -t "${mod}_ready")" = "function" ] && ! "$mod" ready; then
      echo "Module $mod found but not set up"
    fi
  fi
}

# Import an optional module
has() {
  local mod="$1"; shift

  if [[ " $SCMODULES " == *" $mod "* ]]; then
    # Already loaded
    true
  elif [ -r "$SCLIBDIR/$mod" ]; then
    source "$SCLIBDIR/$mod"
    # Add the main entry point
    eval "$mod() { subcall $mod \"\$@\"; }"
  elif [ -r "$SCCMDDIR/$mod" ]; then
    source "$SCCMDDIR/$mod"
    # Add the main entry point
    eval "$mod() { subcall $mod \"\$@\"; }"
  else
    return 2
  fi
  SCMODULES="$SCMODULES $mod"
  if [ "$(type -t "${mod}_enabled")" = "function" ]; then
    if ! "${mod}_enabled"; then
      # The module does not want to exist !
      return 1
    fi
  fi
  if [ "$(type -t "${mod}_ready")" = "function" ]; then
    if ! "${mod}_ready"; then
      # The module is not set up !
      return 1
    fi
  fi
  return 0
}

# Call a method on all commands matching filter
broadcall() {
  local function="$1"; shift

  for f in "$SCCMDDIR"/*; do
    local mod="$(basename "$f")"
    source "$f"
    # Add the main entry point
    eval "$mod() { subcall $mod \"\$@\"; }"
    if [ "$(type -t "${mod}_$function")" = "function" ]; then
      "$mod" "$function" "$@"
    fi
  done
}

# Return the list of all commands.
# takes an optional filter function
cmdlist() {
  local filter="$1"; shift || true

  for f in "$SCCMDDIR"/*; do
    local mod="$(basename "$f")"
    if [ "$filter" ]; then
      source "$f"
      # Add the main entry point
      eval "$mod() { subcall $mod \"\$@\"; }"
      if [ "$(type -t "${mod}_$filter")" != "function" ] || "$mod" "$filter"; then
        echo "$mod"
      fi
    else
      echo "$mod"
    fi
  done
}

# Optionally call a function. Returns true if function missing
optcall() {
  local mod="$1"; shift
  local function="$1"; shift

  if has "$mod" && [ "$(type -t "${mod}_$function")" = "function" ]; then
    "$mod" "$function" "$@"
  fi
}

# Check that command-lines are available, and if some are missing, install the corresponding system package
syspackage() {
  local package="$1"; shift

  require aptpackage setup

  if [ "$#" -eq 0 ]; then
    if apt-get -y install "$package"; then
      return 0
    else
      echo "Cannot install required package $package"
      exit 1
    fi

    return 0
  fi

  for c in "$@"; do
    if ! [ -e "$c" ] && ! which "$c" &>/dev/null; then
      if apt-get -y install "$package"; then
        return 0
      else
        echo "Cannot install required package $package"
        exit 1
      fi
    fi
  done

  return 0
}

git_get() {
  local url="$1"
  local target="$2"
  syspackage git git

  if [ -d "$target/.git" ]; then
    pushd "$target" &>/dev/null
    git clean -dfx
    git pull
    popd &>/dev/null
  elif [ -d "$target" ]; then
    rm -rf "$target"
    git clone "$url" "$target"
  else
    git clone "$url" "$target"
  fi
}

# Returns true if the first parameter is equal to any other parameter
# example:
#  contains standby master standby client
#  Returns true
contains() {
  local value="$1"; shift
  for pattern in "$@"; do
    if [ "$value" = "$pattern" ]; then
      return 0
    fi
  done
  return 1
}
