#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


# Pull files from a remote host
# Used for synchronization
files_pull() {
  local module="$1"; shift
  local host="$1"; shift

  require sshlink

  local files="$(sshlink sc "$host" "$module" files)"
  if [ "$files" ]; then
    sshlink getfiles "$host" <<< "$files"
  fi
}

# Restore files from a backup
files_restoremodule() {
  local module="$1"; shift
  local source="$1"; shift

  require "$module"

  # Check if the module has files
  if ! cancall "$module" files; then return 0; fi

  syspackage rsync rsync
  if [ -d "$source/fs/" ]; then
    "$module" files | rsync -az --delete --files-from=- -r "$source/fs/" "/" || true
  fi
}
