#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


hostconf_setup() {
  require settings

  settings prompt FQDN "$(hostname -f)" "Enter host and domain name (host.example.com)"
  settings save
  broadcall setfqdn "$FQDN"
}

hostconf_host() {
  echo "${FQDN%%.*}"
}

hostconf_domain() {
  echo "${FQDN#*.}"
}

hostconf_fqdn() {
  echo "$FQDN"
}

hostconf_setfqdn() {
  local fqdn="$1"; shift
  echo "$fqdn" > /etc/hostname
  sed -i "s/127\.0\.1\.1 .*/127.0.1.1 $fqdn ${fqdn%%.*}/" /etc/hosts
}

hostconf_ready() {
  if [ "$(hostconf host)" != "localhost" ] && [ "$(hostconf domain)" ] && [ "$(hostconf domain)" != "localdomain" ]; then
    return 0
  fi
  return 1
}

hostconf_settings() {
  echo FQDN
}
