#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


lifeline_setup() {
  require sshlink
  require settings
  require daemon

  settings prompt LIFELINE_TARGET "" "Enter the lifeline target host"
  settings prompt LIFELINE_PORT "22000" "Enter the remote port to open on the target host"
  sshlink add "$LIFELINE_TARGET"
  daemon add lifeline

  settings save
}

lifeline_cleanup() {
  require daemon
  require settings

  daemon del lifeline
  settings del LIFELINE_TARGET
  settings del LIFELINE_PORT

  settings save
}

lifeline_ready() {
  if has daemon && daemon has lifeline && sshlink check "$LIFELINE_TARGET"; then
    return 0
  fi
  return 1
}

lifeline_daemon() {
  exec ssh -o ServerAliveInterval=10 -N -R "$LIFELINE_PORT":localhost:22 "$LIFELINE_TARGET"
}

lifeline_settings() {
  echo "LIFELINE_TARGET"
  echo "LIFELINE_PORT"
}
