#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


mass_setup() {
  require settings
  settings prompt_path MASSDIR "/srv/mass" "Mass storage directory path"

  settings save
}

mass_cleanup() {
  require settings
  unset MASSDIR
  settings save
}

mass_enabled() {
  if [ "$MASSDIR" ] && [ -d "$MASSDIR" ]; then
    return 0
  fi
  return 1
}

mass_ready() {
  if mass enabled; then
    return 0
  fi
  return 1
}

mass_files() {
  if ! has master || [ "$(master mode)" = "master" ]; then
    if mass enabled; then
      echo "$MASSDIR"
    fi
  fi
}

mass_restore() {
  local source="$1"; shift
  require files
  files restoremodule mass "$source"
}

mass_settings() {
  echo MASSDIR
}
