#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


nfssrv_setup() {
  syspackage nfs-kernel-server rpc.nfsd
  mount | grep -e " type btrfs " -e " type fuse.sshfs " -e " type nfs4 " | grep -v -e " on /mnt " -e " on /media " | sed -e 's/.* on \([^ ]*\) .*/\1 *(rw,sync,no_subtree_check)/' > /etc/exports
  sed -i -e '/^\/ /s/no_subtree_check/no_subtree_check,crossmnt,fsid=0/g' /etc/exports
  systemctl reload nfs-kernel-server
}

nfssrv_cleanup() {
  > /etc/exports
  systemctl reload nfs-kernel-server
}

nfssrv_enabled() {
  if [ -e /etc/exports ] && which rpc.nfsd &>/dev/null; then
    return 0
  fi
  return 1
}

nfssrv_ready() {
  if nfssrv enabled && grep -Fx "/ *(rw,sync,no_subtree_check,crossmnt,fsid=0)" /etc/exports &>/dev/null; then
    return 0
  fi
  return 1
}

nfssrv_contains() {
  return 1
}
