#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


sshshare_add() {
  local host="$1"; shift
  local remote="$1"; shift
  local path="$1"; shift || path="$remote"

  require temp
  require sshlink

  syspackage sshfs sshfs

  sshlink add "$host"

  temp file fstab
  grep -vE "[^ ]* $path[/ ]" /etc/fstab > "$fstab"
  cat >> "$fstab" <<EOF
$host:$remote $path fuse.sshfs noauto,x-systemd.automount,_netdev,idmap=user,transform_symlinks,allow_other,default_permissions 0 0
EOF
  mv "$fstab" /etc/fstab
  temp forget fstab

  umount -R "$path"
  mount "$path"
}

sshshare_del() {
  local host="$1"; shift
  local remote="$1"; shift
  local path="$1"; shift || path="$remote"

  umount "$path" || true

  require temp
  temp file fstab
  grep -vFx "$host:$remote $path fuse.sshfs noauto,x-systemd.automount,_netdev,idmap=user,transform_symlinks,allow_other,default_permissions 0 0" /etc/fstab > "$fstab"
  mv "$fstab" /etc/fstab

  temp forget fstab
}

sshshare_has() {
  local path="$1"; shift

  if grep -F " $path fuse.sshfs " /etc/fstab &>/dev/null && mountpoint -q "$path"; then
    return 0
  fi
  return 1
}

sshshare() {
  subcall sshshare "$@"
}
