#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################

update_setup() {
  require settings
  if has master && ! contains "$(master mode)" master; then
    require sshlink
    sshlink importsettings "$MASTER" update
  fi
  settings prompt SCUPDATEURL "https://github.com/retro16/synccluster/archive/master.tar.gz" "$SC update URL"
  settings save
}

update_ready() {
  [ "$SCUPDATEURL" ]
}

update_sync() {
  local host="$1"; shift
  local mode="$1"; shift

  if contains "$mode" master; then return 0; fi

  require sshlink
  sshlink importsettings "$host" update
}

update_start() {
  syspackage wget wget
  syspackage tar tar
  syspackage gzip gzip

  require update setup

  require temp
  temp dir
  wget -qO- "$SCUPDATEURL" | tar -C "$TEMP_FILE" -xvz
  "$TEMP_FILE"/*/"$SC" install
  temp release

  exec "$SCBIN" update upgrade "$SCVERSION"
}

update_upgrade() {
  upgrade_modules "$@"
}

update_settings() {
  echo SCUPDATEURL
}

update_contains() {
  return 1
}
