#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


utils_setup() {
  syspackage screen screen
  syspackage ntp ntpq
  syspackage hdparm hdparm
  syspackage iftop iftop
  syspackage smartmontools smartctl
  syspackage vim /usr/share/doc/vim
  syspackage git git
}

# Utilities useful for a client
utils_client() {
  apt-get install \
    awesome \
    awesome-extra \
    vlc \
    gnome-terminal \
    speedcrunch \
    gmtp \
    pavucontrol \
    task-xfce-desktop \
    lightdm \
    lightdm-gtk-greeter \
    xscreensaver \
    android-tools-adb \
    rawtherapee \
    libreoffice \
    libreoffice-l10n-fr \
    flashplugin-nonfree \
    gimp \
    audacity \
    simple-scan \
    solaar \
    numlockx \
    soundconverter \
    gparted \
    kdenlive \
  -y

  apt-get install -y --no-install-recommends virt-manager gir1.2-spice-client-gtk-3.0 firefox firefox-l10n-fr

  apt-get -y --purge remove iceweasel firefox-esr || true

  if ! [ -e "/etc/apt/sources.list.d/${SC}_owncloud_client.list" ]; then
    echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ /' > "/etc/apt/sources.list.d/${SC}_owncloud_client.list"
    wget -qO- http://download.opensuse.org/repositories/isv:ownCloud:desktop/Debian_8.0/Release.key | apt-key add -
    apt-get update
    apt-get install -y owncloud-client
  fi
}

# Utilities useful for a server
utils_server() {
  apt-get install \
    libvirt-daemon-system \
    qemu-system-x86 \
    qemu-kvm \
    ovmf \
    sgabios \
    debootstrap \
    iotop \
    iftop \
  -y
}

utils_ready() {
  if ! which screen &>/dev/null \
  || ! which ntpq &>/dev/null \
  || ! which hdparm &>/dev/null \
  || ! which iftop &>/dev/null \
  || ! which git &>/dev/null \
  || ! which smartctl &>/dev/null; then
    return 1
  fi
  return 0
}
