#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


www_requires() {
  echo settings
  echo nginx
}

www_setup() {
  require nginx setup

  syspackage apache2 apache2ctl
  syspackage libapache2-mod-php5 /usr/lib/apache2/modules/libphp5.so
  syspackage php5-cli php5
  syspackage php5-apcu /etc/php5/mods-available/apcu.ini
  syspackage php5-curl /usr/share/php5/curl/curl.ini
  syspackage php5-fpm /usr/sbin/php5-fpm
  syspackage php5-gd /usr/share/php5/gd/gd.ini
  syspackage php5-imap /usr/share/php5/imap/imap.ini
  syspackage php5-pgsql /usr/share/php5/pgsql/pgsql.ini

  a2enmod proxy
  a2enmod proxy_http
  a2enmod rewrite

  www configure_apacheredirect /etc/apache2/sites-available/000-default.conf
  www configure_ports /etc/apache2/ports.conf
  www configure_phpini /etc/php5/apache2/php.ini

  systemctl enable apache2
  systemctl restart apache2

  WWWDIR=/var/www
  settings save
}

www_files() {
  echo /etc/php5/apache2/php.ini
  echo "$WWWDIR/html"
}

www_cleanup() {
  unset WWWDIR
  rm "/etc/apache2/conf-available/${SC}_"*.conf
  rm "/etc/apache2/conf-enabled/${SC}_"*.conf
  settings save
}

# Put standard input into an apache conf file and enable it
www_addconf() {
  local conf="$1"; shift
  local target="/etc/apache2/conf-available/${SC}_$conf.conf"
  cat > "$target"
  a2enconf "${SC}_$conf"
  systemctl reload apache2
}

www_hasconf() {
  local conf="$1"; shift
  if [ -e "/etc/apache2/conf-enabled/${SC}_$conf.conf" ]; then
    return 0
  fi
  return 1
}

www_delconf() {
  local conf="$1"; shift
  rm -f "/etc/apache2/conf-available/${SC}_$conf.conf" "/etc/apache2/conf-enabled/${SC}_$conf.conf"
  systemctl reload apache2
}

www_configure_phpini() {
  local target="$1"; shift
  sed -i 's/[ ;]*max_execution_time *= .*/max_execution_time = 1200/' "$target"
  sed -i 's/[ ;]*memory_limit *= .*/memory_limit = 512M/' "$target"
  sed -i 's/[ ;]*post_max_size *= .*/post_max_size = 256M/' "$target"
  sed -i 's/[ ;]*upload_max_filesize *= .*/upload_max_filesize = 2048M/' "$target"
  sed -i 's/[ ;]*date.timezone *= .*/date.timezone = Europe\/Paris/' "$target"
  sed -i 's/[ ;]*upload_max_filesize *= .*/upload_max_filesize = 2048M/' "$target"
}

www_configure_ports() {
  local target="$1"; shift
  cat > "$target" <<EOF
Listen 8080
EOF
}

www_configure_apacheredirect() {
  local target="$1"; shift
  cat > "$target" <<EOF
<VirtualHost *:8080>
    ServerAdmin webmaster@localhost
    DocumentRoot $WWWDIR/html
    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
EOF
}

www_sync() {
  local host="$1"; shift
  local mode="$1"; shift

  if ! contains "$mode" standby; then return 0; fi

  require master
  require sshlink
  sshlink getfiles "$host:$(master getvar WWWDIR)" "$WWWDIR" <<< "html"
}

www_enabled() {
  if [ "$WWWDIR" ]; then
    return 0
  fi
  return 1
}

www_ready() {
  if www enabled && [ -e "/etc/apache2" ] && systemctl status apache2 &>/dev/null; then
    return 0
  fi
  return 1
}

www_settings() {
  echo WWWDIR
}
