#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################

aptpackage_setup() {
  local MIRROR="$(grep -E '^deb [hft]*tp://.*debian.* main' /etc/apt/sources.list | head -n 1 | sed 's;deb \([^ ]*\) [a-z/]* main.*;\1;')"
  local DISTNAME="$(grep -E '^deb [hft]*tp://.*debian.* main' /etc/apt/sources.list | head -n 1 | sed 's;deb [^ ]* \([a-z/]*\) main.*;\1;')"

  cat > /etc/apt/sources.list.d/${SC}_backports.list << EOF
deb $MIRROR $DISTNAME-backports main contrib non-free
deb-src $MIRROR $DISTNAME-backports main contrib non-free
EOF

  cat > /etc/apt/sources.list.d/${SC}_contrib.list << EOF
deb $MIRROR $DISTNAME contrib non-free
deb-src $MIRROR $DISTNAME contrib non-free
EOF

  cat > /etc/apt/sources.list.d/${SC}_firefox.list << EOF
deb http://mozilla.debian.net/ $DISTNAME-backports firefox-release
EOF

  apt update

  require temp
  syspackage wget wget
  temp file
  wget -O"$TEMP_FILE" http://mozilla.debian.net/pkg-mozilla-archive-keyring_1.1_all.deb
  dpkg -i "$TEMP_FILE"
  temp release
}

aptpackage_cleanup() {
  rm -f /etc/apt/sources.list.d/${SC}_backports.list \
        /etc/apt/sources.list.d/${SC}_contrib.list \
        /etc/apt/sources.list.d/${SC}_firefox.list
  apt update
}

aptpackage_ready() {
  if [ -e /etc/apt/sources.list.d/${SC}_backports.list ] && \
     [ -e /etc/apt/sources.list.d/${SC}_contrib.list ] && \
     [ -e /etc/apt/sources.list.d/${SC}_firefox.list ]; then
    return 0
  fi
  return 1
}

aptpackage_help() {
  echo "apt setup: setup backport and contrib apt sources"
  echo "apt cleanup: remove these sources"
}

aptpackage() {
  subcall aptpackage "$@"
}
