#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


# Backs up sc modules


dirbackup_setup() {
  require crontask
  require settings
  require sshlink
  syspackage rsync rsync
  settings prompt DIRBACKUP_ROOT "/srv/backup" "Enter the root path for remote backup"
  if ! [ -d "$DIRBACKUP_ROOT" ]; then
    echo "Invalid backup root path"
    exit 2
  fi
  settings save
  crontask add dirbackup daily
}

dirbackup_clean() {
  require settings
  unset DIRBACKUP_ROOT
  settings save
}

# Add a new path
dirbackup_add() {
  local host="$1"; shift || host="localhost"
  local path="$1"; shift || path="/"
  require settings
  [ -d "$DIRBACKUP_ROOT/$host/fs" ] || mkdir -p "$DIRBACKUP_ROOT/$host/fs"
  DIRBACKUP_LIST="$DIRBACKUP_LIST $host:$path "
  settings save
}

# Remove a path
dirbackup_del() {
  local host="$1"; shift || host="localhost"
  local path="$1"; shift || path="/"
  require settings
  DIRBACKUP_LIST="$(sed -e "s/ $host:$path //" <<< "$DIRBACKUP_LIST")"
}

# Do a backup of one host
dirbackup_backup() {
  local host="$1"; shift || host="localhost"
  local path="$1"; shift || path="/"

  require sshlink
  sshlink getfiles "$host" "$DIRBACKUP_ROOT/$host/fs" <<< "$path"
}

dirbackup_enabled() {
  if [ -z "$DIRBACKUP_ROOT" ] || ! [ -d "$DIRBACKUP_ROOT" ] || [ -z "${DIRBACKUP_LIST}" ]; then
    return 1
  fi
  return 0
}

dirbackup_cron() {
  require temp
  for s in $DIRBACKUP_LIST; do
    dirbackup backup "${s%:*}" "${s#*:}"
  done
}

dirbackup_list() {
  for s in $DIRBACKUP_LIST; do
    echo "$s"
  done
}

dirbackup_settings() {
  echo DIRBACKUP_ROOT
  echo DIRBACKUP_LIST
}

dirbackup() {
  subcall dirbackup "$@"
}


