#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################



nfsclient_add() {
  local host="$1"; shift
  local remote="$1"; shift
  local path="$1"; shift || path="$remote"

  if nfsclient has "$path"; then return 0; fi

  syspackage nfs-common nfsstat

  require temp
  temp file
  grep -vE "[^ ]* $path[/ ]" /etc/fstab > "$TEMP_FILE"
  cat >> "$TEMP_FILE" <<EOF
$host:$remote $path nfs4 rw,rsize=131072,wsize=131072,_netdev,hard,noauto,x-systemd.automount
EOF
  mv "$TEMP_FILE" /etc/fstab
  temp forget

  umount -R "$path" || true
  mount "$path"
}

nfsclient_del() {
  local path="$1"; shift

  umount -R "$path" || true

  require temp
  temp file
  grep -vF " $path nfs4 " /etc/fstab > "$TEMP_FILE"
  mv "$TEMP_FILE" /etc/fstab
  temp forget
}

nfsclient_has() {
  local path="$1"; shift
  if grep -F " $path nfs4 " /etc/fstab &>/dev/null && mountpoint -q "$path"; then
    return 0
  fi
  return 1
}

nfsclient_enabled() {
  if which nfsstat &>/dev/null; then
    return 0
  fi
  return 1
}

nfsclient() {
  subcall nfsclient "$@"
}
