#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


nfsclient_setup() {
  syspackage nfs-common nfsstat
  require temp
  require master setup

  case "$(master mode)" in
  "local")
    nfsclient add "$MASTER" /home
    ;;
  esac
}

nfsclient_add() {
  local host="$1"; shift
  local path="$1"; shift

  local t="$(temp file)"
  grep -vE " $path *nfs4 " /etc/fstab > "$t"
  cat >> "$t" <<EOF
$host:$path $path nfs4 rw,rsize=131072,wsize=131072 0 0
EOF
  mv "$t" /etc/fstab
  temp forget
}

nfsclient_del() {
  local path="$1"; shift

  local t="$(temp file)"
  grep -vE " $path *nfs4 " /etc/fstab > "$t"
  mv "$t" /etc/fstab
  temp forget
}

nfsclient_enabled() {
  if grep ' nfs4 ' /etc/fstab &>/dev/null; then
    return 0
  fi
  return 1
}

nfsclient() {
  subcall nfsclient "$@"
}
