#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


owncloud_version="9.1.0"
owncloud_url="https://download.owncloud.org/community/owncloud-${owncloud_version}.tar.bz2"

owncloud_setup() {
  require www setup
  require temp
  require settings

  settings prompt OWNCLOUD_PASSWORD "" "Owncloud admin and database password:"
  settings prompt CLOUDDIR "/home/.local/cloud" "Owncloud storage path:"

  if ! [ -d "$CLOUDDIR" ]; then
    echo "$CLOUDDIR not found. Aborting."
    exit 2
  fi

  chown -R www-data:www-data "$CLOUDDIR"

  [ -e "$WWWDIR/owncloud" ] || owncloud get
  owncloud apache_conf | www addconf owncloud
  owncloud create_db
  owncloud init
  owncloud config

  chown -R root:www-data "$CLOUDDIR/.htaccess"
}

owncloud_cleanup() {
  require www
  require db

  www delconf owncloud
  rm -rf "$WWWDIR/owncloud"
  db del owncloud owncloud
}

owncloud_get() {
  tmp="$(temp file)"
  wget -O"$tmp" "$owncloud_url"

  tar -C "$WWWDIR" -xvjf "$tmp"
  chown -R www-data:www-data "$WWWDIR/owncloud/apps"
  chown -R www-data:www-data "$WWWDIR/owncloud/config"
  chown -R www-data:www-data "$WWWDIR/owncloud/themes"
  chown -R root:www-data "$WWWDIR/owncloud/.htaccess"

  temp release
}

owncloud_apache_conf() {
  cat <<EOF
Alias /cloud "$WWWDIR/owncloud/"
Redirect 301 /owncloud /cloud

<Directory "$WWWDIR/owncloud">
    Options +FollowSymLinks
    AllowOverride All

    <IfModule mod_dav.c>
      Dav off
    </IfModule>

    SetEnv HOME $WWWDIR/owncloud
    SetEnv HTTP_HOME $WWWDIR/owncloud
</Directory>

<Directory "$CLOUDDIR/">
  # just in case if .htaccess gets disabled
  Require all denied
</Directory>

Redirect 301 /.well-known/carddav /cloud/remote.php/carddav
Redirect 301 /.well-known/caldav  /cloud/remote.php/caldav
EOF
}

owncloud_create_db() {
  require db

  db add owncloud "$OWNCLOUD_PASSWORD" owncloud
}

owncloud_init() {
  owncloud occ maintenance:install --database pgsql --database-name owncloud --database-host localhost --database-user owncloud --database-pass "${OWNCLOUD_PASSWORD}" --admin-user admin --admin-pass "${OWNCLOUD_PASSWORD}" --data-dir "$CLOUDDIR"
}

owncloud_config() {
  require temp
  tmp="$(temp file)"
  head -n -1 "$WWWDIR/owncloud/config/config.php" > "$tmp"
  cat >> "$tmp" <<EOF
  'memcache.local' => '\\\\OC\\\\Memcache\\\\APCu',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{localhost:143/imap/tls/novalidate-cert}INBOX',
      ),
    ),
  ),
);
EOF
  require hostconf setup
  sed -i "/    0 => 'localhost',/a    1 => '$(hostconf domain)'," "$tmp"
  chown www-data:www-data "$tmp"
  mv "$tmp" "$WWWDIR/owncloud/config/config.php"
  temp forget
}

owncloud_occ() {
  trap "sed -i 's;^\\(www-data:.*:\\).*;\\1/usr/sbin/nologin;' /etc/passwd" EXIT
  sed -i 's;^\(www-data:.*:\).*;\1/bin/bash;' /etc/passwd

  pushd "$WWWDIR/owncloud" &>/dev/null
  su -c "php occ $*" www-data
  popd &>/dev/null

  sed -i 's;^\\(www-data:.*:\\).*;\\1/usr/sbin/nologin;' /etc/passwd
  trap EXIT
}

owncloud_db() {
  echo "owncloud:owncloud"
}

owncloud_files() {
  cat <<EOF
$WWWDIR/owncloud/config/config.php
$CLOUDDIR
EOF
}

owncloud_sync() {
  local host="$1"; shift
  local mode="$1"; shift

  if ! contains "$mode" master standby; then return 0; fi

  require db
  db pull owncloud "$host"

  require sshlink
  sshlink getfiles "$host" <<< "$WWWDIR/owncloud/config/config.php"

  require unisonsync
  unisonsync start "$host" "$(sshlink sc "$host" settings get CLOUDDIR)" "$CLOUDDIR"
}

owncloud_ready() {
  if [ -d "$CLOUDDIR" ] && [ -e "$WWWDIR/owncloud/config/config.php" ] && has db && db has owncloud; then
    return 0
  fi
  return 1
}

owncloud_settings() {
  echo OWNCLOUD_PASSWORD
  echo CLOUDDIR
}

owncloud() {
  subcall owncloud "$@"
}
