#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


unisonsync_setup() {
  require settings
  syspackage unison
  settings prompt UNISON "/var/lib/unison" "Enter the UNISON base directory:"
  [ -d "$UNISON" ] || mkdir -p "$UNISON"
  unisonsync common_profile > "$UNISON/_common.prf"
  settings save
}

unisonsync_clean() {
  require settings
  rm -rf "$UNISON"
  unset UNISON
  settings save
}

unisonsync_add() {
  local host="$1"; shift
  local remotepath="$1"; shift
  local localpath="$1"; shift

  cat > "$UNISON/$(unisonsync profilename "$host" "$remotepath").prf" << EOF
include _common
root = $localpath
root = ssh://root@$host/$remotepath
EOF
}

# Returns the name of the profile based on a host and a path
unisonsync_profilename() {
  local host="$1"; shift
  local remotepath="$1"; shift
  echo "${host}$(tr -c '[a-zA-Z0-9]' '_' <<< "$remotepath")"
}

unisonsync_del() {
  local host="$1"; shift
  local path="$1"; shift

  rm "$UNISON/$(unisonsync profilename "$host" "$path").prf"
}

unisonsync_enabled() {
  if [ "$UNISON" ]; then
    return 0
  fi
  return 1
}

unisonsync_ready() {
  if unisonsync enabled && [ -e "$UNISON/_common.prf" ]; then
    return 0
  fi
  return 1
}

unisonsync_files() {
  ls "$UNISON"/[^_.]*.prf
}

# Synchronize profiles from a remote host
unisonsync_sync() {
  local host="$1"; shift
  local mode="$1"; shift

  if contains "$mode" backup client; then return 0; fi

  require files
  files pull unisonsync "$host"
}

# Execute a file synchronization
unisonsync_start() {
  local host="$1"; shift
  local remotepath="$1"; shift
  local localpath="$1"; shift || localpath="$remotepath"

  if ! unisonsync has "$host" "$remotepath"; then
    unisonsync add "$host" "$remotepath" "$localpath"
  fi

  unison "$(unisonsync profilename "$host" "$remotepath")"
}

unisonsync_common_profile() {
cat <<'EOF'
batch = true
times = true
silent = true
retry = 1
addversionno = true
sshargs = -C

owner = true
times = true

prefer = newer

ignore = Regex .*/\.?[cC]ache/.*
ignore = Name [lL]ock
ignore = Name .parentlock
ignore = Name *.[lL]ock
ignore = Name *.nps
ignore = Name *.o
ignore = Name *~
ignore = Name .*~
ignore = Name .[tT]rash*
ignore = Name .*.swp
ignore = Name [Tt]humbs.db
ignore = Name $RECYCLE.BIN
ignore = Name Crash Reports
ignore = Name .nvidia-settings-rc
ignore = Name .dmrc
ignore = Name .xscreensaver
ignore = Name .*authority
ignore = Name .xsession-errors*
ignore = Name .Trash*
ignore = Name .viminfo
ignore = Name .lesshst
ignore = Name .bash_history
ignore = Name .bash_logout
ignore = Name tmp
ignore = Path Documents/HTC
ignore = Path .local
ignore = Path .adobe
ignore = Path .audacity-data
ignore = Path .cache
ignore = Path .dbus
ignore = Path .nv
ignore = Path .wine
ignore = Path .thumbnails
ignore = Path .gstreamer-*
EOF
}

unisonsync() {
  require master
  subcall unisonsync "$@"
}
