#!/bin/bash
###############################################################################
<<LICENSE

The MIT License (MIT)

Copyright (c) 2016 Jean-Matthieu COULON

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

LICENSE
###############################################################################


upnpredir_setup() {
  require settings
  require crontask
  require boot
  syspackage miniupnpc upnpc
  settings prompt UPNPPORTS "22 25 80 143 443 993" "List of ports to redirect to this host:"
  boot add upnpredir
  crontask add upnpredir hourly
  settings save
}

upnpredir_cleanup() {
  require settings
  if has crontask; then
    crontask del upnpredir hourly
  fi
  if has boot; then
    boot del upnpredir
  fi
}

upnpredir_enabled() {
  if [ "$UPNPPORTS" ]; then
    return 0
  fi
  return 1
}

upnpredir_ready() {
  if upnpredir enabled && has boot && boot has upnpredir; then
    return 0
  fi
  return 1
}

upnpredir_refresh() {
  for p in $UPNPPORTS; do
    if ! upnpc -r $p tcp $p udp; then
      upnpc -d $p tcp
      upnpc -d $p udp
      upnpc -r $p tcp $p udp
    fi
  done
}

upnpredir_cron() {
  upnpredir refresh
}

upnpredir_boot() {
  upnpredir refresh
}

upnpredir_settings() {
  echo UPNPPORTS
}

upnpredir() {
  subcall upnpredir "$@"
}
